version: "3.9"
services:
  web:
    build: .
    restart: always
    ports:
      - 3003:3000
    volumes:
      - "./log:/usr/src/app/log"
      - "./index.html:/usr/src/app/index.html"
    platform: linux/x86_64
