services:
  web:
    build: .
    restart: always
    ports:
      - 3003:3000
    volumes:
      # - ./sendmsg-log.log:/usr/src/app/sendmsg-log.log
      - ./index.html:/usr/src/app/index.html
    platform: linux/x86_64
